services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: lnm3_frontend
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL:-http://platform.localhost}
    expose:
      - "3000"
